config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :novels do
    member do
      post :turn_page
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/novel_pagination_concern.rb
module NovelPaginationConcern
  extend ActiveSupport::Concern

  CHAPTER_REGEX = /^==.+==$/

  def fetch_content
    text = file.read

    chapter_title = text.scan(CHAPTER_REGEX)[current_page]
    content = text.split(CHAPTER_REGEX)[1..][current_page]

    [chapter_title, content]
  end

  def next_page
    to_page(current_page + 1)
  end

  def to_page(to_p)
    update!(current_page: to_p)
  end

  def last_page
    to_page(current_page - 1) if current_page.positive?
  end
end

app/models/novel.rb
class Novel < ApplicationRecord
  include ::NovelPaginationConcern

  mount_uploader :file, BookUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include MenusHelper
  def interrput_turbo
    if turbo_frame_request?
      puts params
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :set_novel, only: %i[show edit update destroy turn_page]
  after_action :interrput_turbo

  # GET /novels or /novels.json
  def index
    @novels = Novel.all
  end

  # GET /novels/1 or /novels/1.json
  def show
    @title, @novel_content = @novel.fetch_content
  end

  def turn_page
    commit = params[:commit]&.downcase
    @novel.send("#{commit}_page") if %w[next last].include?(commit)
    @title, @novel_content = @novel.fetch_content

    @title, @novel_content = @novel.fetch_content
    respond_to do |format|
      format.html { render :show }
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('reading', partial: 'novels/novel_content',
                                                             locals: { novel: @novel, page: @page, novel_content: @novel_content })
      end
    end
  end

  # GET /novels/new
  def new
    @novel = Novel.new
  end

  # GET /novels/1/edit
  def edit; end

  # POST /novels or /novels.json
  def create
    @novel = Novel.new(novel_params)

    respond_to do |format|
      if @novel.save
        format.html { redirect_to novel_url(@novel), notice: 'Novel was successfully created.' }
        format.json { render :show, status: :created, location: @novel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /novels/1 or /novels/1.json
  def update
    respond_to do |format|
      if @novel.update(novel_params)
        format.html { redirect_to novel_url(@novel), notice: 'Novel was successfully updated.' }
        format.json { render :show, status: :ok, location: @novel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /novels/1 or /novels/1.json
  def destroy
    @novel.destroy

    respond_to do |format|
      format.html { redirect_to novels_url, notice: 'Novel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_novel
    @novel = Novel.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def novel_params
    params.require(:novel).permit(:title, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
  def menus
    [
      { name: 'Home', path: root_path }
    ]
  end

  def menu_link(name, path)
    link_to_unless controller_name == name.downcase, name.capitalize, path,
                   class: 'block py-2 pr-4 pl-3 bg-blue-700 rounded md:bg-transparent md:p-0 dark:text-white' do
      link_to name.capitalize, path,
              class: 'block py-2 pr-4 pl-3 text-white bg-blue-700 md:text-blue-700 rounded md:bg-transparent md:p-0 dark:text-white'
    end
  end
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/home/index.html.erb
<div class="mx-auto max-w-7xl py-12 px-4 sm:px-6 lg:flex lg:items-center lg:justify-between lg:py-16 lg:px-8">
  <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
    <span class="block">Ready to dive in?</span>
    <span class="block text-indigo-600">Start your free trial today.</span>
  </h2>
  <div class="mt-8 flex lg:mt-0 lg:flex-shrink-0">
    <div class="inline-flex rounded-md shadow">
      <a href="#" class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-5 py-3 text-base font-medium text-white hover:bg-indigo-700">Get started</a>
    </div>
    <div class="ml-3 inline-flex rounded-md shadow">
      <a href="#" class="inline-flex items-center justify-center rounded-md border border-transparent bg-white px-5 py-3 text-base font-medium text-indigo-600 hover:bg-indigo-50">Learn more</a>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="/" class="flex items-center">
        <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Raccoon</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <%= menu_link 'Home', root_path %>
        </li>
        <li>
          <a href="#" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About</a>
        </li>
        <li>
          <%= menu_link 'Novels', novels_path %>
        </li>
        <li>
          <a href="#" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Pricing</a>
        </li>
        <li>
          <a href="#" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raccoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: 'all' %>
    <%= javascript_importmap_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
  </head>

  <body class="bg-gray-50">
    <%= render partial: 'layouts/nav' %>
    <div class="h-screen w-screen">
      <div class="mx-auto">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/novels/_form.html.erb
<%= form_with(model: novel, class: "contents") do |form| %>
  <% if novel.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(novel.errors.count, "error") %> prohibited this novel from being saved:</h2>

      <ul>
        <% novel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :file %>

    <%= form.file_field :file, class: "lock w-full text-sm text-slate-500
      file:mr-4 file:py-2 file:px-4
      file:rounded-full file:border-0
      file:text-sm file:font-semibold
      file:bg-blue-50 file:text-blue-700
      hover:file:bg-blue-100" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/novels/_novel.html.erb
<div id="<%= dom_id novel %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= novel.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">File:</strong>
    <%= novel.file %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this novel", novel, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this novel', edit_novel_path(novel), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/novels/_novel_content.html.erb
<%= turbo_frame_tag 'reading' do %>
  <div class="text-base mt-2 bg-white border-gray-200 px-5 h-4/12 whitespace-pre-line overflow-y-scroll shadow-sm">
    <h1><%= @title %></h1>
    <%= @novel_content %>
  </div>
<% end %>

app/views/novels/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing novel</h1>

  <%= render "form", novel: @novel %>

  <%= link_to "Show this novel", @novel, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to novels", novels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/novels/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Novels</h1>
    <%= link_to 'New novel', new_novel_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="novels" class="min-w-full">
    <%= render @novels %>
  </div>
</div>

app/views/novels/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New novel</h1>

  <%= render "form", novel: @novel %>

  <%= link_to 'Back to novels', novels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/novels/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <div id="info">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>

      <%= render @novel %>

      <%= link_to 'Edit this novel', edit_novel_path(@novel), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to 'Destroy this novel', novel_path(@novel), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
      <%= link_to 'Back to novels', novels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>

    <button id="reading-mode" class="mt-5 rounded-lg py-3 px-5 bg-blue-700 text-white display-block font-medium">Reading Mode</button>
  </div>
</div>
<div class="mx-auto container sm:max-w-screen-sm lg:max-w-screen-lg">
  <%= render partial: 'novel_content' %>
  <%= form_with url: turn_page_novel_url, data: { turbo_frame: :reading }, class: 'flex justify-around pt-2' do |form| %>
    <%= form.hidden_field :format, value: 'turbo_stream' %>
    <%= form.submit 'Last', class: "btn bg-blue-700 hover:bg-blue-800 ml-2 rounded-lg py-3 px-5 text-white bg-green inline-block font-medium submit-buttons", value: 'last', id: 'last-page' %>
    <%= form.submit 'Next', class: "btn bg-blue-700 hover:bg-blue-800 ml-2 rounded-lg py-3 px-5 text-white bg-green inline-block font-medium submit-buttons", value: 'next', id: 'next-page' %>
  <% end %>
</div>

<script>
  let reading = false;
  const readingMode = document.getElementById('reading-mode');
  readingMode.addEventListener('click', () => {
    if (reading) {
      readingMode.innerText = 'Reading Mode';
      document.getElementById('info').style.display = 'block';
      document.getElementById('reading').style.display = 'none';
    } else {
      readingMode.innerText = 'Info Mode';
      document.getElementById('info').style.display = 'none';
      document.getElementById('reading').style.display = 'block';
    }
    reading = !reading;
  });

  document.querySelectorAll('.submit-buttons').forEach((button) => {
    button.addEventListener('click', () => {
      scroll(0,0)
    })
  })

  document.querySelector('html').addEventListener('keydown', (event) => {
    const keyPressed = event.key;
    switch (keyPressed) {
      case 'ArrowRight':
        document.querySelector('#next-page').click()
        break;
       case 'ArrowLeft':
        document.querySelector('#last-page').click()
        break; 
      default:
        break;
    }
  });
</script>